"""add wellness_logs table

Revision ID: d7ad46cf93e8
Revises: 
Create Date: 2026-03-26 12:36:36.711611

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd7ad46cf93e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###